version: '3'
services:
  vietwiss:
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: sail-8.0/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_VIETWISS_PORT:-3000}:80'
      - '${APP_VIETWISS_PORT:-4000}:5173'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL-SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - './:/var/www/html'
    networks:
      - vietwiss
    depends_on:
      - db
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vietwiss
      MYSQL_DATABASE: vietwiss
    networks:
      - vietwiss
    volumes:
      - 'vietwiss-mysql:/var/lib/mysql'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - vietwiss

networks:
  vietwiss:
    driver: bridge
volumes:
  vietwiss:
    driver: local
  vietwiss-mysql:
    driver: local
